version: "3"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ebiz
      - POSTGRES_USER=ebiz
      - POSTGRES_PASSWORD=ebiz
  redis:
    image: library/redis:5.0-alpine
    ports:
      - 6379:6379
    restart: unless-stopped